name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


permissions:
  contents: write

env:
  CSV_URL: "MLproject/student_habits_performance_prepros.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # Print env var
      - name: Check Env
        run: echo $CSV_URL

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      # Run MLflow project
      - name: Run mlflow project
        run: mlflow run MLproject --env-manager=local

      
      - name: Set up Git credentials
        run: |
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

     
      - name: Save mlruns to repo
        run: |
          git add mlruns/
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Save mlruns from CI run"
            git push origin main
          fi
